export default [
  {
    paletteName: "Material UI Colors",
    id: "material-ui-colors",
    emoji: "🎨",
    colors: [
      { name: "red", color: "#F44336" },
      { name: "pink", color: "#E91E63" },
      { name: "purple", color: "#9C27B0" },
      { name: "deeppurple", color: "#673AB7" },
      { name: "indigo", color: "#3F51B5" },
      { name: "blue", color: "#2196F3" },
      { name: "lightblue", color: "#03A9F4" },
      { name: "cyan", color: "#00BCD4" },
      { name: "teal", color: "#009688" },
      { name: "green", color: "#4CAF50" },
      { name: "lightgreen", color: "#8BC34A" },
      { name: "lime", color: "#CDDC39" },
      { name: "yellow", color: "#FFEB3B" },
      { name: "amber", color: "#FFC107" },
      { name: "orange", color: "#FF9800" },
      { name: "deeporange", color: "#FF5722" },
      { name: "brown", color: "#795548" },
      { name: "grey", color: "#9E9E9E" },
      { name: "bluegrey", color: "#607D8B" }
    ]
  },
  {
    paletteName: "Flat UI Colors v1",
    id: "flat-ui-colors-v1",
    emoji: "🤙",
    colors: [
      { name: "Turquoise", color: "#1abc9c" },
      { name: "Emerald", color: "#2ecc71" },
      { name: "PeterRiver", color: "#3498db" },
      { name: "Amethyst", color: "#9b59b6" },
      { name: "WetAsphalt", color: "#34495e" },
      { name: "GreenSea", color: "#16a085" },
      { name: "Nephritis", color: "#27ae60" },
      { name: "BelizeHole", color: "#2980b9" },
      { name: "Wisteria", color: "#8e44ad" },
      { name: "MidnightBlue", color: "#2c3e50" },
      { name: "SunFlower", color: "#f1c40f" },
      { name: "Carrot", color: "#e67e22" },
      { name: "Alizarin", color: "#e74c3c" },
      { name: "Clouds", color: "#ecf0f1" },
      { name: "Concrete", color: "#95a5a6" },
      { name: "Orange", color: "#f39c12" },
      { name: "Pumpkin", color: "#d35400" },
      { name: "Pomegranate", color: "#c0392b" },
      { name: "Silver", color: "#bdc3c7" },
      { name: "Asbestos", color: "#7f8c8d" }
    ]
  },
  {
    paletteName: "Spectrum Flat",
    id: "spectrum-flat",
    emoji: "US",
    colors: [
      { name: "Sunflower", color: "#FFC312" },
      { name: "Energos", color: "#C4E538" },
      { name: "BlueMartina", color: "#12CBC4" },
      { name: "LavenderRose", color: "#FDA7DF" },
      { name: "BaraRose", color: "#ED4C67" },
      { name: "RadiantYellow", color: "#F79F1F" },
      { name: "AndroidGreen", color: "#A3CB38" },
      { name: "MediterraneanSea", color: "#1289A7" },
      { name: "LavenderTea", color: "#D980FA" },
      { name: "VerryBerry", color: "#B53471" },
      { name: "PuffinsBill", color: "#EE5A24" },
      { name: "PixelatedGrass", color: "#009432" },
      { name: "MerchantMarineBlue", color: "#0652DD" },
      { name: "ForgottenPurple", color: "#9980FA" },
      { name: "HollyHock", color: "#833471" },
      { name: "RedPigment", color: "#EA2027" },
      { name: "TurkishAqua", color: "#006266" },
      { name: "20000LeaguesUnderTheSea", color: "#1B1464" },
      { name: "CircumorbitalRing", color: "#5758BB" },
      { name: "MagentaPurple", color: "#6F1E51" }
    ] 
  },
  {
    paletteName: "Toronto Blue Jays Flat",
    id: "toronto-blue-jays-a",
    emoji: "CA",
    colors: [
      { name: "parrot", color: "#3579DC" },
      { name: "pollock blue", color: "#4D6FAC" },
      { name: "cornflowerblue", color: "#6495ED" },
      { name: "ulysses butterfly", color: "#1464F4" },
      { name: "alaska sky", color: "#1B3F8B" },
      { name: "Ghost Color", color: "#f8f8ff" },
      { name: "Titan White", color: "#EEEEFF" },
      { name: "Foam", color: "#f7fcfe" },
      { name: "Native Alien", color: "#fcfcfc" },
      { name: "Snow White", color: "#fffafa" },
      { name: "Black Bean", color: "#010302" },
      { name: "Steel Gray", color: "#262335" },
      { name: "Diesel", color: "#020001" },
      { name: "Onyx", color: "#0f0f0f" },
      { name: "Dark Night", color: "#030200" },
      { name: "Grey", color: "#808080" },
      { name: "Dark Grey", color: "#A9A9A9" },
      { name: "Silver", color: "#C0C0C0" },
      { name: "Light Grey", color: "#D3D3D3" },
      { name: "Gains Boro", color: "#DCDCDC" }
    ]
  },
  {
    paletteName: "Toronto Raptors Flat",
    id: "toronto-raptors-a",
    emoji: "CA",
    colors: [
      { name: "Black Bean", color: "#010302" },
      { name: "Steel Gray", color: "#262335" },
      { name: "Diesel", color: "#020001" },
      { name: "Onyx", color: "#0f0f0f" },
      { name: "Dark Night", color: "#030200" },
      { name: "Grey", color: "#808080" },
      { name: "Dark Grey", color: "#A9A9A9" },
      { name: "Silver", color: "#C0C0C0" },
      { name: "Light Grey", color: "#D3D3D3" },
      { name: "Gains Boro", color: "#DCDCDC" },
      { name: "Indigo", color: "#4B0082" },
      { name: "Dark Magenta", color: "#8B008B" },
      { name: "Darkorchid", color: "#9932CC" },
      { name: "Dark Violet", color: "#9400D3" },
      { name: "Blue Violet", color: "#8A2BE2" },
      { name: "Red", color: "#FF0000" },
      { name: "Fire Brick", color: "#B22222" },
      { name: "Crimson", color: "#DC143C" },
      { name: "Indian Red", color: "#CD5C5C" },
      { name: "Light Coral", color: "#F08080" }
    ]
  },
  {
    paletteName: "Philadelphia Eagles Flat",
    id: "philadelphia-eagles-flat-a",
    emoji: "US",
    colors: [
      { name: "Ghost Color", color: "#f8f8ff" },
      { name: "Titan White", color: "#EEEEFF" },
      { name: "Foam", color: "#f7fcfe" },
      { name: "Native Alien", color: "#fcfcfc" },
      { name: "Snow White", color: "#fffafa" },
      { name: "Black Bean", color: "#010302" },
      { name: "Steel Gray", color: "#262335" },
      { name: "Diesel", color: "#020001" },
      { name: "Onyx", color: "#0f0f0f" },
      { name: "Dark Night", color: "#030200" },
      { name: "fresh green", color: "#5EDA9E" },
      { name: "ooze", color: "#3E7A5E" },
      { name: "green bark", color: "#597368" },
      { name: "seagreen", color: "#238E68" },
      { name: "mediumaquamarine", color: "#66CDAA" },
      { name: "aquamarine", color: "#7FFFD4" },
      { name: "garden hose", color: "#138F6A" },
      { name: "blue green algae", color: "#3B8471" },
      { name: "cooler", color: "#284942" },
      { name: "green ash", color: "#668E86" }
    ]
  }
];

